<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kristen Flaws">
<meta name="keywords" content="social network size, frontal alpha asymmetry, fear, temperament, infancy">
<meta name="description" content="SOCIAL NETWORK SIZE, FRONTAL ALPHA ASYMMETRY, &amp; TEMPERAMENT">

<title>The relationship between social network size and frontal alpha asymmetry to strangers during infancy: The moderation of temperament</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="SNQ-FAA-Data_files/libs/clipboard/clipboard.min.js"></script>
<script src="SNQ-FAA-Data_files/libs/quarto-html/quarto.js"></script>
<script src="SNQ-FAA-Data_files/libs/quarto-html/popper.min.js"></script>
<script src="SNQ-FAA-Data_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="SNQ-FAA-Data_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="SNQ-FAA-Data_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="SNQ-FAA-Data_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="SNQ-FAA-Data_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="SNQ-FAA-Data_files/libs/bootstrap/bootstrap-61c9f5fe3bf7f1d5f9219c551e9df0c2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="SNQ-FAA-Data_files/libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="SNQ-FAA-Data_files/libs/tabwid-1.1.3/tabwid.js"></script>
<script src="SNQ-FAA-Data_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="SNQ-FAA-Data_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="_extensions/wjschne/apaquarto/apa.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-methods" id="toc-sec-methods" class="nav-link active" data-scroll-target="#sec-methods">Methods</a>
  <ul class="collapse">
  <li><a href="#sec-participants" id="toc-sec-participants" class="nav-link" data-scroll-target="#sec-participants">Participants</a></li>
  <li><a href="#sec-procedure" id="toc-sec-procedure" class="nav-link" data-scroll-target="#sec-procedure">Procedure</a></li>
  <li><a href="#sec-analyses" id="toc-sec-analyses" class="nav-link" data-scroll-target="#sec-analyses">Analyses</a></li>
  </ul></li>
  <li><a href="#sec-results" id="toc-sec-results" class="nav-link" data-scroll-target="#sec-results">Results</a></li>
  <li><a href="#sec-discussion" id="toc-sec-discussion" class="nav-link" data-scroll-target="#sec-discussion">Discussion</a></li>
  <li><a href="#sec-references" id="toc-sec-references" class="nav-link" data-scroll-target="#sec-references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="SNQ-FAA-Data.docx"><i class="bi bi-file-word"></i>MS Word (apaquarto)</a></li><li><a href="SNQ-FAA-Data.pdf"><i class="bi bi-file-pdf"></i>Typst (apaquarto)</a></li><li><a href="SNQ-FAA-Data.pdf"><i class="bi bi-file-pdf"></i>PDF (apaquarto)</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">




<br>

<br>

<section id="title" class="level1 title unnumbered unlisted">
<h1 class="title unnumbered unlisted">The relationship between social network size and frontal alpha asymmetry to strangers during infancy: The moderation of temperament</h1>
<div class="Author">
<br>

<p>Kristen Flaws</p>
<p>MA Program in the Social Sciences, University of Chicago</p>
</div>
</section>
<section id="author-note" class="level1 unnumbered unlisted AuthorNote">
<h1 class="unnumbered unlisted AuthorNote">Author Note</h1>
</section>
<section id="abstract" class="level1 unnumbered unlisted AuthorNote">
<h1 class="unnumbered unlisted AuthorNote">Abstract</h1>
<div class="AbstractFirstParagraph">
<p>Multiple previous studies have reported the close relationship between children’s social network size and social cognition. However, the connection between social network size and social emotional development has been less examined. The current study aims to examine the connection between infants’ social network sizes and their neural response to strangers, as a pointer to their social emotional development. We will examine how social network sizes are related to neural responses to strangers during infancy using an infant’s frontal alpha asymmetry (FAA), measuring alpha wave frequency, as a neural indicator. Additionally, we will investigate how temperament, especially fear, can moderate the relationship between social network size and responses to strangers during infancy. Our study will use an Electroencephalogram (EEG) machine to measure the infant’s neural processing of strangers, specifically alpha wave frequency, and in turn calculate the infant’s FAA while watching videos of strangers. In order to measure an infant’s temperament and social network size, parents will be instructed to fill out the Revised Infant Behavior Questionnaire (IBQ-R) and Child Social Network Questionnaire (CSNQ). We found that larger social network sizes are associated with more positive FAA while viewing the videos of strangers, however, there is only a weak correlation. We found that fear acts as a moderator, which increases the effectiveness of social network size on infant’s responses to strangers. The findings of this study will contribute to the understanding of the neurological reactions, and affecting factors, toward strangers during infancy.</p>
</div>
<p><em>Keywords</em>: social network size, frontal alpha asymmetry, fear, temperament, infancy</p>
</section>
<section id="firstheader" class="level1 title unnumbered unlisted">
<h1 class="title unnumbered unlisted">The relationship between social network size and frontal alpha asymmetry to strangers during infancy: The moderation of temperament</h1>
<p>Infants learn about the world from the people around them. An infant’s social network allows them to explore the world and learn how to connect and communicate with others. It has been previously suggested that children with a larger social network size are better at taking others’ perspectives <span class="citation" data-cites="burkeChildrensSocialNetwork2023">(<a href="#ref-burkeChildrensSocialNetwork2023" role="doc-biblioref">Burke et al., 2023</a>)</span>. In the current study, we aim to expand these findings from behavioral domain to neural domain and examine the relation between children’s social network size and their neural responses to strangers during infancy.</p>
<section id="sec-lit-review" class="level2">
<h2 data-anchor-id="sec-lit-review">Literature Review</h2>
<section id="sec-social-network-size" class="level3">
<h3 data-anchor-id="sec-social-network-size">Social Network Size</h3>
<p>Previous studies found that social networks play an important role in social cognition throughout infancy and childhood <span class="citation" data-cites="burkeChildrensSocialNetwork2023 burkeChildrensSocialNetworks2022">(<a href="#ref-burkeChildrensSocialNetworks2022" role="doc-biblioref">Burke et al., 2022</a>, <a href="#ref-burkeChildrensSocialNetwork2023" role="doc-biblioref">2023</a>)</span>. Burke and colleagues <span class="citation" data-cites="burkeChildrensSocialNetwork2023">(<a href="#ref-burkeChildrensSocialNetwork2023" role="doc-biblioref">2023</a>)</span> examined the relation between a three year-old’s social network size and their perspective-taking skills. The researchers were observing the children’s basic understanding that what they see may be different from what someone else sees <span class="citation" data-cites="burkeChildrensSocialNetwork2023">(<a href="#ref-burkeChildrensSocialNetwork2023" role="doc-biblioref">Burke et al., 2023</a>)</span>. The results revealed that children with larger social networks displayed significantly better explicit perspective-taking skills. This finding indicates that a larger social network might improve a child’s ability to consider things from another person’s point of view, or on the other hand,better perspective taking skills can help children build a larger social network <span class="citation" data-cites="burkeChildrensSocialNetwork2023">(<a href="#ref-burkeChildrensSocialNetwork2023" role="doc-biblioref">Burke et al., 2023</a>)</span>.</p>
<p>Some indirect findings also support the role of social networks on the development of social cognition. It has been previously found that children aged 5-11 with at least one sibling are more likely to develop positive peer relationships because having a sibling allows children to have more opportunities to develop social and interpersonal skills during early childhood <span class="citation" data-cites="downeyPlayingWellOthers2004">(<a href="#ref-downeyPlayingWellOthers2004" role="doc-biblioref">Downey &amp; Condron, 2004</a>)</span>. These findings support the close relationship between children’s social network size and social cognition. However, the connection between social network size and social emotional development has been less examined. In addition, most studies focused on older children, the role of social network size during the first year of life remains unclear.</p>
<p>Based on these gaps in previous studies, the current study will examine the relationship between social network size and response to strangers of infants from 8 - 12 months of age. More specifically, we will focus on infants’ neural responses, frontal alpha asymmetry (FAA), while watching socially interactive videos of strangers.</p>
</section>
<section id="sec-frontal-alpha-asymmetry" class="level3">
<h3 data-anchor-id="sec-frontal-alpha-asymmetry">Frontal Alpha Asymmetry</h3>
<p>Frontal alpha asymmetry (FAA) is an important neural indicator of infants’ approach/withdrawal tendency <span class="citation" data-cites="davidsonfox_1982_asymmetrical foxdavidson_1986_tasteelicited fox_1991_if gartsteinStudyingInfantTemperament2003 harrewijnFrontalAlphaAsymmetry2019 howarthFrontalElectroencephalogramAsymmetry2016">(<a href="#ref-davidsonfox_1982_asymmetrical" role="doc-biblioref">Davidson &amp; Fox, 1982</a>; <a href="#ref-fox_1991_if" role="doc-biblioref">Fox, 1991</a>; <a href="#ref-foxdavidson_1986_tasteelicited" role="doc-biblioref">Fox &amp; Davidson, 1986</a>; <a href="#ref-gartsteinStudyingInfantTemperament2003" role="doc-biblioref">Gartstein &amp; Rothbart, 2003</a>; <a href="#ref-harrewijnFrontalAlphaAsymmetry2019" role="doc-biblioref">Harrewijn et al., 2019</a>; <a href="#ref-howarthFrontalElectroencephalogramAsymmetry2016" role="doc-biblioref">Howarth et al., 2016</a>)</span>. FAA is the measurement of the imbalance in cortical activation between the right and left frontal hemispheres, measured by psycho-physiological markers using electroencephalogram (EEG) <span class="citation" data-cites="fox_1991_if foxdavidson_1986_tasteelicited davidsonfox_1982_asymmetrical">(<a href="#ref-davidsonfox_1982_asymmetrical" role="doc-biblioref">Davidson &amp; Fox, 1982</a>; <a href="#ref-fox_1991_if" role="doc-biblioref">Fox, 1991</a>; <a href="#ref-foxdavidson_1986_tasteelicited" role="doc-biblioref">Fox &amp; Davidson, 1986</a>)</span>. Rightward/negative FAA signifies increased right hemispheric activation as compared to left and leftward/positive FAA signifies increased left hemispheric activation <span class="citation" data-cites="vincentetal_2021_using">(<a href="#ref-vincentetal_2021_using" role="doc-biblioref">Vincent et al., 2021</a>)</span>. FAA is thought to be a moderator reflecting fearful inhibition and impulsivity-anger <span class="citation" data-cites="liuFrontalEEGAsymmetry2021">(<a href="#ref-liuFrontalEEGAsymmetry2021" role="doc-biblioref">Liu et al., 2021</a>)</span>, with left FAA being associated with higher levels of activity/approach while right FAA is associated with higher levels of fear/withdrawal <span class="citation" data-cites="davidsonfox_1982_asymmetrical foxdavidson_1986_tasteelicited fox_1991_if gartsteinStudyingInfantTemperament2003 harrewijnFrontalAlphaAsymmetry2019 howarthFrontalElectroencephalogramAsymmetry2016">(<a href="#ref-davidsonfox_1982_asymmetrical" role="doc-biblioref">Davidson &amp; Fox, 1982</a>; <a href="#ref-fox_1991_if" role="doc-biblioref">Fox, 1991</a>; <a href="#ref-foxdavidson_1986_tasteelicited" role="doc-biblioref">Fox &amp; Davidson, 1986</a>; <a href="#ref-gartsteinStudyingInfantTemperament2003" role="doc-biblioref">Gartstein &amp; Rothbart, 2003</a>; <a href="#ref-harrewijnFrontalAlphaAsymmetry2019" role="doc-biblioref">Harrewijn et al., 2019</a>; <a href="#ref-howarthFrontalElectroencephalogramAsymmetry2016" role="doc-biblioref">Howarth et al., 2016</a>)</span>. Based on these findings, we will use FAA as a neural indicator of infants’ approach/withdrawal tendency towards strangers.</p>
<p>It is advantageous to utilize FAA to study the relationship between social network size and infants’ responses to strangers because neural indicators can be more sensitive than behavioral indicators <span class="citation" data-cites="davidsonfox_1982_asymmetrical foxdavidson_1986_tasteelicited fox_1991_if harrewijnFrontalAlphaAsymmetry2019 howarthFrontalElectroencephalogramAsymmetry2016">(<a href="#ref-davidsonfox_1982_asymmetrical" role="doc-biblioref">Davidson &amp; Fox, 1982</a>; <a href="#ref-fox_1991_if" role="doc-biblioref">Fox, 1991</a>; <a href="#ref-foxdavidson_1986_tasteelicited" role="doc-biblioref">Fox &amp; Davidson, 1986</a>; <a href="#ref-harrewijnFrontalAlphaAsymmetry2019" role="doc-biblioref">Harrewijn et al., 2019</a>; <a href="#ref-howarthFrontalElectroencephalogramAsymmetry2016" role="doc-biblioref">Howarth et al., 2016</a>)</span>. The behavioral changes of 8- to 12-month-olds might be too subtle to code, whereas neural indicators can be more sensitive to capture individual differences, given that FAA has been widely used to study individual differences <span class="citation" data-cites="gollanFrontalAlphaEEG2014">(e.g.&nbsp;motivation, affect, depression severity, <a href="#ref-gollanFrontalAlphaEEG2014" role="doc-biblioref">Gollan et al., 2014</a>)</span>. Furthermore, examining the relationship between social network size and FAA can enhance our understanding of how social networks may shape infant’s brains.</p>
<p>Previous studies suggest that larger social network sizes are associated with better perspective-taking skills <span class="citation" data-cites="burkeChildrensSocialNetwork2023">(<a href="#ref-burkeChildrensSocialNetwork2023" role="doc-biblioref">Burke et al., 2023</a>)</span> and social and interpersonal skills <span class="citation" data-cites="downeyPlayingWellOthers2004">(<a href="#ref-downeyPlayingWellOthers2004" role="doc-biblioref">Downey &amp; Condron, 2004</a>)</span>, which indicates a positive relationship between social network sizes and social development. In the current study, we also expect social network sizes to be related to more positive responses to strangers. Since positive FAA is associated with approach tendencies in infants <span class="citation" data-cites="davidsonfox_1982_asymmetrical foxdavidson_1986_tasteelicited fox_1991_if">(<a href="#ref-davidsonfox_1982_asymmetrical" role="doc-biblioref">Davidson &amp; Fox, 1982</a>; <a href="#ref-fox_1991_if" role="doc-biblioref">Fox, 1991</a>; <a href="#ref-foxdavidson_1986_tasteelicited" role="doc-biblioref">Fox &amp; Davidson, 1986</a>)</span>, we hypothesize that an infant with a larger social network will be more likely to display more positive FAA to strangers.</p>
</section>
<section id="sec-moderating-effect-of-temperament" class="level3">
<h3 data-anchor-id="sec-moderating-effect-of-temperament">The Moderating Effect of Temperament</h3>
<p>Temperament was found to play a large role in an infant’s responses to strangers <span class="citation" data-cites="rubinSocialWithdrawlChildhood2009">(<a href="#ref-rubinSocialWithdrawlChildhood2009" role="doc-biblioref">Rubin et al., 2009</a>)</span>. Children who are shy or display reticent behavior will show more avoidance to strangers <span class="citation" data-cites="rubinSocialWithdrawlChildhood2009">(<a href="#ref-rubinSocialWithdrawlChildhood2009" role="doc-biblioref">Rubin et al., 2009</a>)</span>. Furthermore, children with different temperament will react to the same environment differently, or in other words, temperament can moderate the effect of the environment on child development. Ertekin and colleagues <span class="citation" data-cites="ertekinTemperamentModeratesEffects2021">(<a href="#ref-ertekinTemperamentModeratesEffects2021" role="doc-biblioref">2021</a>)</span> found that infants with a more reactive temperament, including higher levels of fear, irritability, and activity may be more sensitive to the surrounding environment as they are more likely to be overwhelmed. More specifically, infants with a higher rate of recovery from distress were less impacted by adverse environments than infants with a low rate of recovery from distress <span class="citation" data-cites="ertekinTemperamentModeratesEffects2021">(<a href="#ref-ertekinTemperamentModeratesEffects2021" role="doc-biblioref">Ertekin et al., 2021</a>)</span>. Another study found that temperament can moderate children’s social wariness towards strangers of the same race and different races than their own <span class="citation" data-cites="hwangChildrensSocialWariness2023">(i.e.&nbsp;‘ingroup’ versus ‘outgroup,’ <a href="#ref-hwangChildrensSocialWariness2023" role="doc-biblioref">Hwang et al., 2023</a>)</span>. More shy children displayed greater social wariness towards strangers of a different race than of the same race to their own, while less shy children did not <span class="citation" data-cites="hwangChildrensSocialWariness2023">(<a href="#ref-hwangChildrensSocialWariness2023" role="doc-biblioref">Hwang et al., 2023</a>)</span>. These findings suggest that individual differences in temperament can have a moderating effect between social environment and children’s responses to strangers.</p>
<p>Based on these findings, the current study will examine the moderating role of temperament between social network size and infants’ FAA to strangers. Specifically, we will focus on the fear dimension, which refers to the level of fearfulness or anxiousness in response to novel or unfamiliar stimuli <span class="citation" data-cites="gartsteinStudyingInfantTemperament2003">(<a href="#ref-gartsteinStudyingInfantTemperament2003" role="doc-biblioref">Gartstein &amp; Rothbart, 2003</a>)</span>, given that this dimension is viewed as an important characteristic during the first year of life.</p>
</section>
</section>
<section id="sec-current-study" class="level2">
<h2 data-anchor-id="sec-current-study">Current Study</h2>
<p>The current study aims to examine two questions. First, this study will examine the relationship between social network sizes and neural responses to strangers during infancy. We used an infant’s FAA as an indicator of the infant’s neural response to strangers. Given the positive relation between social network sizes and children’ social cognition <span class="citation" data-cites="burkeChildrensSocialNetwork2023 downeyPlayingWellOthers2004">(<a href="#ref-burkeChildrensSocialNetwork2023" role="doc-biblioref">Burke et al., 2023</a>; <a href="#ref-downeyPlayingWellOthers2004" role="doc-biblioref">Downey &amp; Condron, 2004</a>)</span>, we predicted that larger social network size will correlate with more positive FAA (i.e.&nbsp;increased left frontal activation) toward strangers.</p>
<p>Second, we are interested in how temperament, especially fear, can moderate the relationship between social network size and an infant’s responses to strangers. There are several possibilities. One possibility is that infants’ temperamental fear may magnify the association between social network size and FAA to strangers, given that infants with greater fear were found to have more sensitivity to the influence of environments <span class="citation" data-cites="ertekinTemperamentModeratesEffects2021">(<a href="#ref-ertekinTemperamentModeratesEffects2021" role="doc-biblioref">Ertekin et al., 2021</a>)</span>. In addition, if infants show greater fear of novel stimuli and also exhibit more negative FAA to strangers, parents might be more reluctant to introduce new environments and new people to infants, leading to smaller social networks. Another possibility could be that infants’ temperamental fear might weaken the association between social network size and FAA to strangers. Infants with greater fear might show negative FAA to strangers regardless of their social network sizes, while infants with less fear might be more likely to benefit from having a larger social network, thereby showing more positive FAA to strangers.</p>
<p>In summary, this study aimed to examine the connection between infants’ social network sizes and their neural response to strangers. It contributes to the understanding of how early social environments can shape infants’ brains and how individual temperament plays a moderating role. These factors are essential in understanding an infant’s stranger anxiety/fear and are important for caregivers to take into consideration when scaffolding infants build their social networks.</p>
</section>
</section>
<section id="sec-methods" class="level1">
<h1>Methods</h1>
<p>This study uses EEG recordings in combination with parent reports to measure an infant’s social network size, temperamental fear, and FAA in response to strangers.</p>
<section id="sec-participants" class="level3">
<h3 data-anchor-id="sec-participants">Participants</h3>
<p>All participants in this study were recruited by the Infant Learning and Development Laboratory at the University of Chicago. The parents of approximately 80 infants from 8 months to 12 months old were asked to participate in the study. Inclusion criteria is as follows: (1) 8 to 12 months of age, (2) English language spoken at least 80% of the time at home, (3) full-term; 37 weeks and beyond gestational age, and (4) no developmental delays.</p>
</section>
<section id="sec-procedure" class="level3">
<h3 data-anchor-id="sec-procedure">Procedure</h3>
<p>Our study uses an Electroencephalogram (EEG) machine and related materials (i.e.&nbsp;infant EEG cap, software, and technical equipment) to measure the infant’s neural processing of strangers, specifically alpha wave frequency. During the EEG task, infants watched videos of two strangers grasping a toy alternatively. One stranger speaks English, and the other speaks French. Our analyses focus on infants’ neural responses while watching the native speaker. To calculate FAA, we subtracted the natural log-transformed relative alpha power of the 6-9 Hz frequency band in the left hemisphere from the natural log-transformed relative alpha power in the right hemisphere <span class="citation" data-cites="anayaetal_2021_psychometric vincentetal_2021_using foxContinuityDiscontinuityBehavioral2001">(<a href="#ref-anayaetal_2021_psychometric" role="doc-biblioref">Anaya et al., 2021</a>; <a href="#ref-foxContinuityDiscontinuityBehavioral2001" role="doc-biblioref">Fox et al., 2001</a>; <a href="#ref-vincentetal_2021_using" role="doc-biblioref">Vincent et al., 2021</a>)</span>. Therefore, in our calculations of FAA, stronger left frontal activation is indicated by a positive FAA score <span class="citation" data-cites="harrewijnFrontalAlphaAsymmetry2019 vincentetal_2021_using">(<a href="#ref-harrewijnFrontalAlphaAsymmetry2019" role="doc-biblioref">Harrewijn et al., 2019</a>; <a href="#ref-vincentetal_2021_using" role="doc-biblioref">Vincent et al., 2021</a>)</span>.</p>
<p>Infant social network information will be measured by parent report with the Child Social Network Questionnaire (CSNQ), a demographic form for each person the child sees on a regular basis <span class="citation" data-cites="burkeChildrensSocialNetworks2022">(<a href="#ref-burkeChildrensSocialNetworks2022" role="doc-biblioref">Burke et al., 2022</a>)</span>. For the purposes of this study, we were interested in the size of an infants’ social network and calculated the number of people within each participants’ social network.</p>
<p>In order to measure an infant’s temperamental fear, parents were instructed to fill out the Revised Infant Behavior Questionnaire (IBQ-R), a parent report of a reaction on a seven point scale during the past one or two weeks <span class="citation" data-cites="gartsteinStudyingInfantTemperament2003">(<a href="#ref-gartsteinStudyingInfantTemperament2003" role="doc-biblioref">Gartstein &amp; Rothbart, 2003</a>)</span>, The fear subscale contains 16 items related to an infants’ ‘startle or distress to sudden changes in stimulation, novel physical objects or social stimuli; inhibited approach to novelty’ <span class="citation" data-cites="gartsteinStudyingInfantTemperament2003">(<a href="#ref-gartsteinStudyingInfantTemperament2003" role="doc-biblioref">Gartstein &amp; Rothbart, 2003</a>)</span>. We will use the average point rating across the 16 items as an infant’s temperamental fear score.</p>
</section>
<section id="sec-analyses" class="level3">
<h3 data-anchor-id="sec-analyses">Analyses</h3>
<p>This study uses linear mixed models (LMM) to examine our hypotheses. First, to examine the relationship between social network sizes and infants’ neural responses to strangers, we conducted a LMM, on FAA of each action window (reaching and grasping), with social network size and language condition as the fixed effects and subject ID as a random effect. Second, to examine the moderating effect of temperamental fear between social network sizes and infants’ responses to strangers, we conducted a LMM on FAA of each action window (reaching, grasping), with social network size, temperamental fear, their interaction, and the language condition as the fixed effects and subject ID as a random effect.</p>
</section>
</section>
<section id="sec-results" class="level1">
<h1>Results</h1>
<p>The results presented below will accomplish the following aims. First, we present the descriptive information about the variables. Next we aim to answer the question: what is the relationship between social network size and frontal alpha asymmetry in infants? And finally, we will look at the potential moderating effect of temperament, specifically fear, between the realtionship of social network size and FAA.</p>
<div class="cell FigureWithNote" data-apa-note="Table 1 displays social network size (SNQ) and FAA data for the first three participants." prefix="" data-tblnum="1" data-custom-style="FigureWithNote">
<div id="tbl-snq-faa" class="cell quarto-float quarto-figure quarto-figure-center" prefix="" data-apa-note="Table 1 displays social network size (SNQ) and FAA data for the first three participants." data-tblnum="1">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-snq-faa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Social Network Size and FAA Data (First 6 Rows)</p>
</div>
</figcaption>
<div aria-describedby="tbl-snq-faa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-89c900b8{}.cl-89c0f8d2{font-family:'Times New Roman';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-89c52bc8{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-89c547d4{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-89c547de{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-89c547df{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-89c900b8"><thead><tr style="overflow-wrap:break-word;"><th class="cl-89c547d4"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">ID</span></p></th><th class="cl-89c547d4"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">SNS</span></p></th><th class="cl-89c547d4"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">Time</span></p></th><th class="cl-89c547d4"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">FAA</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">PB_10</span></p></td><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">11</span></p></td><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">0 to 1000</span></p></td><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">0.02</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">PB_10</span></p></td><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">11</span></p></td><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">-1000 to 0</span></p></td><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">0.01</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">PB_11</span></p></td><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">17</span></p></td><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">0 to 1000</span></p></td><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">0.02</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">PB_11</span></p></td><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">17</span></p></td><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">-1000 to 0</span></p></td><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">0.04</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">PB_13</span></p></td><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">3</span></p></td><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">0 to 1000</span></p></td><td class="cl-89c547de"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">-0.02</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-89c547df"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">PB_13</span></p></td><td class="cl-89c547df"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">3</span></p></td><td class="cl-89c547df"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">-1000 to 0</span></p></td><td class="cl-89c547df"><p class="cl-89c52bc8"><span class="cl-89c0f8d2">-0.02</span></p></td></tr></tbody></table></div>
</div>
</div>
</figure>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Table 1 displays social network size (SNQ) and FAA data for the first three participants.</p>
</div>
</div>
<p><a href="#tbl-snq-faa" class="quarto-xref" aria-expanded="false">Table&nbsp;1</a> displays examples of social network size, as measured by the SNQ, and FAA data. Each participant has two instances of measured FAA. The -1000 to 0 time frame represents FAA while the actor in the video was reaching towards an object while the 0 to 1000 time frame represents FAA while the actor in the video was grasping an object.</p>
<p><a href="#tbl-summary-statistics-sns" class="quarto-xref" aria-expanded="false">Table&nbsp;2</a> and <a href="#tbl-summary-statistics-faa" class="quarto-xref" aria-expanded="false">Table&nbsp;3</a> display descriptive information about social network size and FAA respectively. There are 152 participants in this study with a mean social network size of 10.89 and a mean level of FAA of 0.01.</p>
<div class="cell FigureWithoutNote" prefix="" data-tblnum="2" data-custom-style="FigureWithoutNote">
<div id="tbl-summary-statistics-sns" class="cell quarto-float quarto-figure quarto-figure-center" data-tblnum="2" prefix="">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-statistics-sns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;2</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Descriptive Statistics - Social Network Size</p>
</div>
</figcaption>
<div aria-describedby="tbl-summary-statistics-sns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Descriptive Statistics - Social Network Size</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean SNS</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Median SNS</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD SNS</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Min SNS</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Max SNS</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Range SNS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">10.89</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">5.34</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">23</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<div class="cell FigureWithoutNote" prefix="" data-tblnum="3" data-custom-style="FigureWithoutNote">
<div id="tbl-summary-statistics-faa" class="cell quarto-float quarto-figure quarto-figure-center" data-tblnum="3" prefix="">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-statistics-faa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;3</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Descriptive Statistics - FAA</p>
</div>
</figcaption>
<div aria-describedby="tbl-summary-statistics-faa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Descriptive Statistics - FAA</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean FAA</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Median FAA</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD FAA</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Min FAA</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Max FAA</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Range FAA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">0.16</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p><a href="#fig-scatter-sns-faa" class="quarto-xref" aria-expanded="false">Figure&nbsp;1</a> demonstrates the relationship between social network size and FAA for each participant during the two time periods: watching the stranger reach towards an object and grasping/lifting the object. As we can see, FAA has a tendency to increase as social network size increases. This supports our hypothesis that a larger social network size will lead to more positive FAA.</p>
</div>
<p>The difference in levels of FAA between the participant with the highest and lowest social network size is 0.04.</p>
<div class="cell FigureWithNote" data-apa-note="Figure 1 displays levels of FAA and infants' social network sizes." data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-scatter-sns-faa" class="quarto-float quarto-figure quarto-figure-center" data-fignum="1" prefix="">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-scatter-sns-faa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Social Network Size and FAA by Time Blocks</p>
</div>
</figcaption>
<div aria-describedby="fig-scatter-sns-faa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="SNQ-FAA-Data_files/figure-html/fig-scatter-sns-faa-1.svg" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Figure 1 displays levels of FAA and infants’ social network sizes.</p>
</div>
<div class="cell FigureWithoutNote" prefix="" data-tblnum="4" data-custom-style="FigureWithoutNote">
<div id="tbl-lmm-faa-sns" class="cell quarto-float quarto-figure quarto-figure-center" data-tblnum="4" prefix="">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lmm-faa-sns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;4</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Linear Mixed Model between FAA and SNS</p>
</div>
</figcaption>
<div aria-describedby="tbl-lmm-faa-sns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table style="border-collapse:collapse; border:none;">
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">&nbsp;</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">FAA</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">p</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">df</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.295</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">148.00</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">SNS</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.00</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>0.030</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">148.00</td>
</tr>

<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">ICC</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.87</td>
</tr><tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">152</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">Marginal R<sup>2</sup> / Conditional R<sup>2</sup></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.056 / 0.880</td>
</tr>

</tbody></table>

</div>
</div>
</figure>
</div>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>However, from <a href="#tbl-lmm-faa-sns" class="quarto-xref" aria-expanded="false">Table&nbsp;4</a> we can see this relationship is not statistically significant (<em>p</em> = .030). The marginal R-squared = 0.056, which means that only 5.6% of the variance is explained by the fixed effects of social network size and the conditional R-squared = 0.88, which suggests that a large portion of the variance is explained by random effects or individual differences. The ICC of 0.824 emphasizes that random effects dominate the variance in this model.</p>
</div>
<p><a href="#fig-total-sample-scatter" class="quarto-xref" aria-expanded="false">Figure&nbsp;2</a> displays social network size and FAA including temepramental fear as a moderator. The darker the data points the higher the levels of parent reported fear. From the figure, we can see that as social network size increases, FAA also increases. Additionally, the gradient of temperamental fear demonstrates infant’s with higher fear have both more negative FAA and smaller social network sizes.</p>
<p>There are 4 less participants in this model as only 72 completed all three aspects of this study (SNQ, IBQ, and EEG measuring).</p>
<div class="cell FigureWithNote" data-apa-note="Figure 2 displays levels of FAA and social network sizes including a gradient of temperamental fear level. Darker data points indicate a higher level of parent reported fear." data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-total-sample-scatter" class="quarto-float quarto-figure quarto-figure-center" data-fignum="2" prefix="">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-total-sample-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;2</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Social Network Size, FAA, and Fear Level</p>
</div>
</figcaption>
<div aria-describedby="fig-total-sample-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="SNQ-FAA-Data_files/figure-html/fig-total-sample-scatter-1.svg" class="img-fluid figure-img" width="576">
</div>
</figure>
</div>
</div>
</div>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Figure 2 displays levels of FAA and social network sizes including a gradient of temperamental fear level. Darker data points indicate a higher level of parent reported fear.</p>
</div>
<div class="cell FigureWithoutNote" prefix="" data-tblnum="5" data-custom-style="FigureWithoutNote">
<div id="tbl-lmm-total-sample" class="cell quarto-float quarto-figure quarto-figure-center" data-tblnum="5" prefix="">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lmm-total-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;5</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Linear Mixed Model: FAA, Temperament, Social Network Size</p>
</div>
</figcaption>
<div aria-describedby="tbl-lmm-total-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table style="border-collapse:collapse; border:none;">
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">&nbsp;</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">FAA</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">p</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">df</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.605</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">135.00</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">SNS</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.00</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.971</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">135.00</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">mean IBQ</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.00</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.418</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">135.00</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Time [0 to 1000]</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.00</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.588</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">135.00</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">SNS × mean IBQ</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.00</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.635</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">135.00</td>
</tr>

<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">ICC</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.88</td>
</tr><tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">142</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">Marginal R<sup>2</sup> / Conditional R<sup>2</sup></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.063 / 0.886</td>
</tr>

</tbody></table>

</div>
</div>
</figure>
</div>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>However, again, these relationships are not significant as seen in <a href="#tbl-lmm-total-sample" class="quarto-xref" aria-expanded="false">Table&nbsp;5</a> (<em>p</em> = .635). The marginal R-squared = 0.063, which tells us that only 6.3% of the variance is explained by the fixed effects of social network size and fear as measured by the SNQ and IBQ respectively. While this is low, there was a slight increase of in comparison to our first model where only 5.6% of the variance was explained by fixed effects. This increase suggests that level of temperamental fear does have an impact on the relationship between social network size and FAA. The conditional R-squared = 0.886, which suggests that 88.6% of the variance is explained by random effects or individual differences. This is about the same as the first model. The ICC of 0.823 emphasizes that random effects dominate the variance in this model as well as the first.</p>
</div>
</section>
<section id="sec-discussion" class="level1">
<h1>Discussion</h1>
<p>The aim of our study was to answer two questions: what is the relationship between social network size and FAA in infants towards strangers and what is the moderating effect of fear in this relationship?</p>
<p>We have found evidence to support our first hypothesis, that a larger social network size is associated with more positive FAA while viewing the videos of strangers. However, the evidence is not statistically significant and the variance is largely explained by individual differences. One limitation to proving our hypothesis was our small sample size. Further research is needed to provide more conclusive results.</p>
<p>Due to the evidence relating to our first hypothesis, we were further interested in the moderating effect of fear in this relationship. We have found that a high level of fear magnified the relationship between social network size and an infant’s neural response to strangers, seen through the increase in variance explained by the fixed effects.</p>
<p>The findings of this study will contribute to the understanding of the neurological reactions, and affecting factors, toward strangers during infancy.</p>
</section>
<section id="sec-references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-anayaetal_2021_psychometric" class="csl-entry" role="listitem">
Anaya, B., Ostlund, B., LoBue, V., Buss, K., &amp; Pérex-Edgar, K. (2021). Psychometric properties of infant electroencephalography: <span>Developmental</span> stability, reliability, and construct validity of frontal alpha asymmetry and delta–beta coupling. <em>Developmental Psychobiology</em>, <em>63</em>(6). <a href="https://doi.org/10.1002/dev.22178">https://doi.org/10.1002/dev.22178</a>
</div>
<div id="ref-burkeChildrensSocialNetwork2023" class="csl-entry" role="listitem">
Burke, N., Brezack, N., Meyer, M., &amp; Woodward, A. (2023). Children’s social network size is related to their perspective-taking skills. <em>Frontiers in Developmental Psychology</em>, <em>1</em>. <a href="https://doi.org/10.3389/fdpys.2023.1221056">https://doi.org/10.3389/fdpys.2023.1221056</a>
</div>
<div id="ref-burkeChildrensSocialNetworks2022" class="csl-entry" role="listitem">
Burke, N., Brezack, N., &amp; Woodward, A. (2022). Children’s social networks in developmental psychology: <span>A</span> network approach to capture and describe early social environments. <em>Frontiers in Psychology</em>, <em>13</em>, 1009422. <a href="https://doi.org/10.3389/fpsyg.2022.1009422">https://doi.org/10.3389/fpsyg.2022.1009422</a>
</div>
<div id="ref-davidsonfox_1982_asymmetrical" class="csl-entry" role="listitem">
Davidson, R. J., &amp; Fox, N. A. (1982). Asymmetrical brain activity discriminates between positive and negative affective stimuli in human infants. <em>Science</em>, <em>218</em>(4578), 1235–1237. <a href="https://doi.org/10.1126/science.7146906">https://doi.org/10.1126/science.7146906</a>
</div>
<div id="ref-downeyPlayingWellOthers2004" class="csl-entry" role="listitem">
Downey, D. B., &amp; Condron, D. J. (2004). Playing <span>Well</span> with <span>Others</span> in <span>Kindergarten</span>: <span>The Benefits</span> of <span>Siblings</span> at <span>Home</span>. <em>Journal of Marriage and Family</em>, <em>66</em>, 330–350. <a href="https://doi.org/10.1111/j.1741-3737.2004.00024.x">https://doi.org/10.1111/j.1741-3737.2004.00024.x</a>
</div>
<div id="ref-ertekinTemperamentModeratesEffects2021" class="csl-entry" role="listitem">
Ertekin, Z., Gunnar, M. R., &amp; Berument, S. K. (2021). Temperament moderates the effects of early deprivation on infant attention. <em>The Official Journal of the International Congress of Infant Studies</em>, <em>26</em>(3), 455–468. https://doi.org/<a href="https://doi-org.proxy.uchicago.edu/10.1111/infa.12396">https://doi-org.proxy.uchicago.edu/10.1111/infa.12396</a>
</div>
<div id="ref-fox_1991_if" class="csl-entry" role="listitem">
Fox, N. A. (1991). If it’s not left, it’s right: <span>Electroencephalograph</span> asymmetry and the development of emotion. <em>American Psychologist</em>, <em>46</em>(8), 863–872. <a href="https://doi.org/10.1037/0003-066X.46.8.863">https://doi.org/10.1037/0003-066X.46.8.863</a>
</div>
<div id="ref-foxdavidson_1986_tasteelicited" class="csl-entry" role="listitem">
Fox, N. A., &amp; Davidson, R. J. (1986). Taste-elicited changes in facial signs of emotion and the asymmetry of brain electrical activity in human newborns. <em>Neuropsychologia</em>, <em>24</em>(3), 417–422. https://doi.org/<a href="https://doi.org/10.1016/0028-3932(86)90028-X">https://doi.org/10.1016/0028-3932(86)90028-X</a>
</div>
<div id="ref-foxContinuityDiscontinuityBehavioral2001" class="csl-entry" role="listitem">
Fox, N. A., Henderson, H. A., Rubin, K. H., Calkins, S. D., &amp; Schmidt, L. A. (2001). Continuity and discontinuity of behavioral inhibition and exuberance: Psychophysiological and behavioral influences across the first four years of life. <em>Child Development</em>, <em>72</em>(1), 1–21. <a href="https://doi.org/10.1111/1467-8624.00262">https://doi.org/10.1111/1467-8624.00262</a>
</div>
<div id="ref-gartsteinStudyingInfantTemperament2003" class="csl-entry" role="listitem">
Gartstein, M. A., &amp; Rothbart, M. K. (2003). Studying infant temperament via the <span>Revised Infant Behavior Questionnaire</span>. <em>Infant Behavior &amp; Development</em>, <em>26</em>, 64–86.
</div>
<div id="ref-gollanFrontalAlphaEEG2014" class="csl-entry" role="listitem">
Gollan, J. K., Hoxha, D., Chihade, D., Pflieger, M. E., Rosebrock, L., &amp; Cacioppo, J. (2014). Frontal alpha <span>EEG</span> asymmetry before and after behavioral activation treatment for depression. <em>Biological Psychology</em>, <em>99</em>, 198–208. <a href="https://doi.org/10.1016/j.biopsycho.2014.03.003">https://doi.org/10.1016/j.biopsycho.2014.03.003</a>
</div>
<div id="ref-harrewijnFrontalAlphaAsymmetry2019" class="csl-entry" role="listitem">
Harrewijn, A., Buzzell, G. A., Debnath, R., Leibenluft, E., Pine, D. S., &amp; Fox, N. A. (2019). Frontal alpha asymmetry moderates the relations between behavioral inhibition and social-effect <span>ERN</span>. <em>Biological Psychology</em>, <em>141</em>, 10–16. <a href="https://doi.org/doi:10.1016/j.biopsycho.2018.12.014">https://doi.org/doi:10.1016/j.biopsycho.2018.12.014</a>
</div>
<div id="ref-howarthFrontalElectroencephalogramAsymmetry2016" class="csl-entry" role="listitem">
Howarth, G. Z., Fettig, N. B., Curby, T. W., &amp; Bell, M. A. (2016). Frontal <span>Electroencephalogram Asymmetry</span> and <span>Temperament Across Infancy</span> and <span>Early Childhood</span>: <span>An Exploration</span> of <span>Stability</span> and <span>Bidirectional Relations</span>. <em>Child Development</em>, <em>87</em>(2), 465–476. <a href="https://doi.org/10.1111/cdev.12466">https://doi.org/10.1111/cdev.12466</a>
</div>
<div id="ref-hwangChildrensSocialWariness2023" class="csl-entry" role="listitem">
Hwang, G., Filippi, C. A., Morales, S., Fox, N. A., &amp; Woodward, A. (2023). Children’s social wariness toward a different-race stranger relates to individual differences in temperament. <em>Developmental Science</em>, <em>e13390</em>. <a href="https://doi.org/10.1111/desc.13390">https://doi.org/10.1111/desc.13390</a>
</div>
<div id="ref-liuFrontalEEGAsymmetry2021" class="csl-entry" role="listitem">
Liu, R., Calkins, S. D., &amp; Bell, M. A. (2021). Frontal <span>EEG</span> asymmetry moderates the associations between negative temperament and behavioral problems during childhood. <em>Development and Psychopathology</em>, <em>33</em>(3), 1016–1025. <a href="https://doi.org/10.1017/S0954579420000309">https://doi.org/10.1017/S0954579420000309</a>
</div>
<div id="ref-rubinSocialWithdrawlChildhood2009" class="csl-entry" role="listitem">
Rubin, K. H., Coplan, R. J., &amp; Bowker, J. C. (2009). Social <span>Withdrawl</span> in <span>Childhood</span>. <em>Annual Review of Psychology</em>.
</div>
<div id="ref-vincentetal_2021_using" class="csl-entry" role="listitem">
Vincent, K. M., Xie, W., &amp; Nelson, C. A. (2021). Using different methods for calculating frontal alpha asymmetry to study its development from infancy to 3 years of age in a large longitudinal sample. <em>Development Psychobiology</em>, <em>63</em>. https://doi.org/<a href="https://doi-org.proxy.uchicago.edu/10.1002/dev.22163">https://doi-org.proxy.uchicago.edu/10.1002/dev.22163</a>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>